# Generated by Django 3.2.6 on 2021-11-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.IntegerField(primary_key=True, serialize=False, verbose_name='UserId')),
                ('age', models.IntegerField(unique=True, verbose_name='age')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=200, unique=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, unique=True, verbose_name='last name')),
                ('gender', models.CharField(max_length=15, unique=True, verbose_name='gender')),
                ('emergency_name', models.CharField(max_length=200, unique=True, verbose_name='emergency contact name')),
                ('emergency_email', models.EmailField(max_length=60, unique=True, verbose_name='emergency email address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
