# Generated by Django 3.2.9 on 2021-11-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_email',
            field=models.EmailField(max_length=60, verbose_name='emergency email address'),
        ),
    ]
