# Generated by Django 3.2.9 on 2021-11-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_emergency_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Type', max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
