# Generated by Django 3.2.9 on 2021-11-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_emergency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=15, verbose_name='gender'),
        ),
    ]
