# Generated by Django 3.2.9 on 2021-11-09 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211109_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='drugpublish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
