# Generated by Django 3.2.9 on 2021-11-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_pill_drugpublish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='last name')),
                ('phone', models.CharField(max_length=20, verbose_name='contact number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('gender', models.CharField(max_length=15, verbose_name='gender')),
                ('emergency_name', models.CharField(max_length=200, verbose_name='emergency contact name')),
                ('emergency_email', models.EmailField(max_length=60, verbose_name='emergency email address')),
                ('user_type', models.CharField(default='Type A', max_length=50, verbose_name='User Type')),
                ('filled_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
