# Generated by Django 3.2.6 on 2021-11-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_pill_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pill',
        ),
    ]
