# Generated by Django 3.2.6 on 2021-11-11 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211111_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='emergency contact name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='filled_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(default='Type A', max_length=50, verbose_name='User Type'),
        ),
    ]
