# Generated by Django 3.2.6 on 2021-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20211111_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='emergency_email',
            field=models.EmailField(max_length=60, null=True, unique=True, verbose_name='emergency email address'),
        ),
    ]
