# Generated by Django 3.2.9 on 2021-11-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_myuser_emergency_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='age'),
        ),
    ]
