# Generated by Django 3.2.9 on 2021-11-13 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_myuser_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='drug_comments',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='drug comments'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='drug_frequency'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='drug qty'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='drug type'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='exp_date',
            field=models.DateTimeField(null=True, verbose_name='expiry date'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='man_date',
            field=models.DateTimeField(null=True, verbose_name='manufacturing date'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
