# Generated by Django 3.2.9 on 2021-11-17 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20211114_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
