# Generated by Django 3.2.9 on 2021-11-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_medicine_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='start_date',
        ),
    ]
