# Generated by Django 3.2.9 on 2021-11-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20211117_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='points'),
        ),
    ]
