# Generated by Django 3.2.9 on 2021-11-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_myuser_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='drug_time',
            field=models.TimeField(blank=True, null=True, verbose_name='drug time'),
        ),
    ]
